// ==UserScript==
// @name 页面关键字搜索
// @description 页面关键字搜索：高亮、结果列表、历史、多关键字、正则、快捷键、单条复制、同源 iframe 与可调磨砂玻璃 UI。
// @match *://*/*
// @run-at document-end
// @grant GM.log
// @grant GM.getValue
// @grant GM.setValue
// @grant GM.registerMenuCommand
// ==/UserScript==

// @ts-nocheck

declare const GM: any

(() => {
  const ROOT_ID = "scripting-page-search-root"
  const STYLE_ID = "scripting-page-search-style"
  const MARK_CLASS = "scripting-page-search-mark"
  const ACTIVE_CLASS = "scripting-page-search-active"
  const STORAGE_KEY = "scripting-page-search-config-v4"
  const HISTORY_KEY = "scripting-page-search-history-v1"
  const HISTORY_LIMIT = 20
  const RESULT_LIMIT = 100
  const defaultConfig = { position: "bottom", caseSensitive: false, regex: false, multiKeyword: true, searchIframes: true, showResults: true, glass: true, opacity: 86, blur: 18, iconScale: 1, uiWidthScale: 1, accentColor: "#2563eb", highlightColor: "#fde047", activeColor: "#fb923c", shortcutEnabled: true, shortcutKey: "k", floatingPosition: null }
  let config = { ...defaultConfig }, history: string[] = [], matches: HTMLElement[] = [], activeIndex = -1, keyword = ""
  const clampNumber = (value: any, min: number, max: number, fallback: number) => { const n = Number(value); return Number.isFinite(n) ? Math.min(max, Math.max(min, n)) : fallback }
  const isHexColor = (value: any) => /^#[0-9a-f]{6}$/i.test(String(value || ""))
  const normalizeConfig = (value: any = {}) => {
    const source = value && typeof value === "object" ? value : {}, next = { ...defaultConfig, ...source }
    if (!["bottom", "top", "topbar"].includes(next.position)) next.position = defaultConfig.position
    next.opacity = clampNumber(next.opacity, 0, 100, defaultConfig.opacity); next.blur = clampNumber(next.blur, 0, 35, defaultConfig.blur)
    next.iconScale = clampNumber(next.iconScale, 1, 2, defaultConfig.iconScale); next.uiWidthScale = clampNumber(next.uiWidthScale, 1, 2, defaultConfig.uiWidthScale)
    next.accentColor = isHexColor(next.accentColor) ? next.accentColor : defaultConfig.accentColor; next.highlightColor = isHexColor(next.highlightColor) ? next.highlightColor : defaultConfig.highlightColor; next.activeColor = isHexColor(next.activeColor) ? next.activeColor : defaultConfig.activeColor
    next.shortcutKey = (String(next.shortcutKey || defaultConfig.shortcutKey).slice(0, 1).toLowerCase() || defaultConfig.shortcutKey)
    next.floatingPosition = next.floatingPosition && typeof next.floatingPosition === "object" ? { x: Number(next.floatingPosition.x) || 0, y: Number(next.floatingPosition.y) || 0 } : null
    ;["caseSensitive", "regex", "multiKeyword", "searchIframes", "showResults", "glass", "shortcutEnabled"].forEach((key) => { next[key] = !!next[key] })
    return next
  }
  const normalizeHistory = (items: any) => { const seen = new Set(); return (Array.isArray(items) ? items : []).map((x) => String(x || "").trim()).filter((x) => x && !seen.has(x) && seen.add(x)).slice(0, HISTORY_LIMIT) }
  const escapeRegExp = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
  const escapeHtml = (s: string) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#039;")
  async function loadStored(key: string, fallback: any) { try { const v = await GM.getValue?.(key, null); if (v != null) return typeof v === "string" ? JSON.parse(v) : v } catch {} try { return JSON.parse(localStorage.getItem(key) || JSON.stringify(fallback)) } catch { return fallback } }
  function saveStored(key: string, value: any) { try { localStorage.setItem(key, JSON.stringify(value)) } catch {} try { GM.setValue?.(key, value) } catch {} }
  const root = () => document.getElementById(ROOT_ID), input = () => document.querySelector<HTMLInputElement>(`#${ROOT_ID} .ps-input`), status = () => document.querySelector<HTMLElement>(`#${ROOT_ID} .ps-status`)
  const setStatus = (text: string) => { const el = status(); if (el) el.textContent = text }
  const getDocs = () => { const docs = [document]; if (config.searchIframes) document.querySelectorAll("iframe,frame").forEach((f: any) => { try { if (f.contentDocument?.body) docs.push(f.contentDocument) } catch {} }); return docs }
  function addStyle() { if (document.getElementById(STYLE_ID)) return; const style = document.createElement("style"); style.id = STYLE_ID; style.textContent = `#${ROOT_ID}{position:fixed;right:8px;bottom:56px;z-index:2147483647;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;--ps-accent:${config.accentColor};--ps-highlight:${config.highlightColor};--ps-active:${config.activeColor}}#${ROOT_ID}.ps-top{top:8px;bottom:auto}#${ROOT_ID}.ps-topbar{top:5px;bottom:auto;left:6px;right:6px}#${ROOT_ID} *{box-sizing:border-box}#${ROOT_ID} button{cursor:pointer}#${ROOT_ID} .ps-toggle{width:38px;height:38px;border:1px solid #bfdbfe;border-radius:999px;background:rgba(255,255,255,.86);color:var(--ps-accent);box-shadow:0 6px 16px #2563eb29}#${ROOT_ID} .ps-panel{display:none;width:min(340px,calc(100vw - 12px));max-height:56vh;overflow:auto;padding:8px;border:1px solid #cbd5e1;border-radius:12px;background:rgba(255,255,255,.92);box-shadow:0 8px 18px #0f172a33}#${ROOT_ID}.ps-open .ps-toggle{display:none}#${ROOT_ID}.ps-open .ps-panel{display:block}#${ROOT_ID} .ps-row{display:flex;gap:6px;margin:6px 0}#${ROOT_ID} input,#${ROOT_ID} select{height:32px;border:1px solid #cbd5e1;border-radius:8px;padding:0 7px;font-size:16px}#${ROOT_ID} .ps-input{flex:1;min-width:0}#${ROOT_ID} .ps-nav,#${ROOT_ID} .ps-search{border:0;border-radius:8px;padding:0 10px;height:32px;background:var(--ps-accent);color:white}#${ROOT_ID} .ps-status{font-size:12px;color:#64748b}#${ROOT_ID} .ps-result,#${ROOT_ID} .ps-history-item{display:block;width:100%;border:0;border-bottom:1px solid #e2e8f0;background:#f8fafccc;text-align:left;padding:6px;color:#334155}. ${MARK_CLASS}{background:var(--ps-highlight)!important;color:#111827!important;border-radius:3px}. ${MARK_CLASS}.${ACTIVE_CLASS}{background:var(--ps-active)!important;outline:2px solid var(--ps-active)}`.replace(/\. /g,"."); document.documentElement.appendChild(style) }
  function applyAppearance() { const el = root(); if (!el) return; el.classList.toggle("ps-top", config.position === "top"); el.classList.toggle("ps-topbar", config.position === "topbar"); el.style.setProperty("--ps-accent", config.accentColor); el.style.setProperty("--ps-highlight", config.highlightColor); el.style.setProperty("--ps-active", config.activeColor) }
  function saveConfig(options: any = {}) { config = normalizeConfig(config); saveStored(STORAGE_KEY, config); applyAppearance(); if (options.renderResults !== false) renderResults() }
  function saveHistory() { history = normalizeHistory(history); saveStored(HISTORY_KEY, history); renderHistory() }
  function clear() { getDocs().forEach((doc) => doc.querySelectorAll(`.${MARK_CLASS}`).forEach((m: any) => { const p = m.parentNode; if (p) { p.replaceChild(doc.createTextNode(m.textContent || ""), m); p.normalize() } })); matches = []; activeIndex = -1; keyword = ""; renderResults() }
  const isSearchableElement = (el: HTMLElement) => { for (let n: any = el; n && n !== n.ownerDocument.documentElement; n = n.parentElement) { if (n.id === ROOT_ID || n.hidden || n.getAttribute("aria-hidden") === "true") return false; if (["SCRIPT","STYLE","TEXTAREA","INPUT","SELECT","OPTION"].includes(n.tagName)) return false; const s = getComputedStyle(n); if (s.display === "none" || s.visibility === "hidden" || s.opacity === "0") return false } return true }
  function buildMatchers(value: string) { const flags = config.caseSensitive ? "g" : "gi"; const terms = config.regex || !config.multiKeyword ? [value] : value.split(/[，,\n]+|\s{2,}/).map((x) => x.trim()).filter(Boolean); return terms.map((term) => ({ term, re: new RegExp(config.regex ? term : escapeRegExp(term), flags) })) }
  function search() { const value = input()?.value.trim() || ""; clear(); if (!value) return setStatus("请输入要查找的关键字"); let ms: any[]; try { ms = buildMatchers(value) } catch (e: any) { return setStatus(`正则表达式错误：${e.message || e}`) } keyword = value; getDocs().forEach((doc) => { const walker = doc.createTreeWalker(doc.body, NodeFilter.SHOW_TEXT); const nodes: Text[] = []; let n: any; while ((n = walker.nextNode())) if (n.parentElement && isSearchableElement(n.parentElement) && ms.some((m) => { m.re.lastIndex = 0; return m.re.test(n.nodeValue || "") })) nodes.push(n); nodes.forEach((node) => { const text = node.nodeValue || "", ranges: any[] = []; ms.forEach((m, termIndex) => { m.re.lastIndex = 0; let r; while ((r = m.re.exec(text))) { if (!r[0]) { m.re.lastIndex++; continue } ranges.push({ start: r.index, end: r.index + r[0].length, termIndex }) } }); ranges.sort((a,b)=>a.start-b.start||b.end-a.end); const frag = doc.createDocumentFragment(); let last=0,end=0; ranges.forEach((r)=>{ if(r.start<end)return; if(r.start>last)frag.appendChild(doc.createTextNode(text.slice(last,r.start))); const mark=doc.createElement("mark"); mark.className=MARK_CLASS; mark.textContent=text.slice(r.start,r.end); frag.appendChild(mark); matches.push(mark); last=end=r.end }); if(last<text.length)frag.appendChild(doc.createTextNode(text.slice(last))); node.parentNode?.replaceChild(frag,node) }) }); if (!matches.length) return setStatus(`未找到可在当前页面定位的“${value}”`); history = [value, ...history.filter((x) => x !== value)].slice(0, HISTORY_LIMIT); saveHistory(); activeIndex = 0; updateActive(); GM.log?.(`页面关键字搜索：找到 ${matches.length} 个“${value}”`) }
  function snippet(mark: HTMLElement) { const t = (mark.parentElement?.textContent || mark.textContent || "").replace(/\s+/g," ").trim(); return t.slice(0, 120) }
  function renderResults() { const list = document.querySelector<HTMLElement>(`#${ROOT_ID} .ps-result-list`); if (!list) return; if (!config.showResults || !matches.length) { list.innerHTML = ""; return } const max = Math.min(matches.length, RESULT_LIMIT); list.innerHTML = matches.slice(0,max).map((m,i)=>`<button class="ps-result" data-index="${i}"><b>${i+1}.</b> ${escapeHtml(snippet(m))}</button>`).join("") }
  function renderHistory() { const list = document.querySelector<HTMLElement>(`#${ROOT_ID} .ps-history-list`); if (list) list.innerHTML = history.map((h,i)=>`<button class="ps-history-item" data-index="${i}">${escapeHtml(h)}</button>`).join("") || `<div class="ps-status">暂无搜索历史</div>` }
  function updateActive() { matches.forEach((m) => m.classList.remove(ACTIVE_CLASS)); const m = matches[activeIndex]; if (!m) return renderResults(); m.classList.add(ACTIVE_CLASS); m.scrollIntoView({ behavior: "smooth", block: "center", inline: "center" }); setStatus(`“${keyword}”：第 ${activeIndex + 1} / ${matches.length} 个结果`); renderResults() }
  function go(step: number) { if (!matches.length) return setStatus("请先搜索关键字"); activeIndex = (activeIndex + step + matches.length) % matches.length; updateActive() }
  const shouldHandleConfigEvent = (event: Event) => { const target = event.target; if (!(target instanceof HTMLInputElement) && !(target instanceof HTMLSelectElement)) return false; if (event.type === "input") return target.matches('input[type="range"], input[type="color"], input[type="text"]'); if (event.type === "change") return target.matches('input[type="checkbox"], input[type="range"], input[type="color"], select'); return true }
  function handleConfigChange(event: Event) { if (!shouldHandleConfigEvent(event)) return; const t: any = event.target; if (t.classList.contains("ps-config-position")) config.position = t.value; if (t.classList.contains("ps-config-case")) config.caseSensitive = t.checked; if (t.classList.contains("ps-config-regex")) config.regex = t.checked; if (t.classList.contains("ps-config-multi")) config.multiKeyword = t.checked; if (t.classList.contains("ps-config-iframes")) config.searchIframes = t.checked; if (t.classList.contains("ps-config-results")) config.showResults = t.checked; if (t.classList.contains("ps-config-shortcut-enabled")) config.shortcutEnabled = t.checked; if (t.classList.contains("ps-config-shortcut")) config.shortcutKey = (t.value || "k").slice(0,1).toLowerCase(); saveConfig() }
  function createPanel() { addStyle(); const el = document.createElement("div"); el.id = ROOT_ID; el.innerHTML = `<button class="ps-toggle" title="搜索页面关键字">🔎</button><div class="ps-panel"><div class="ps-row"><input class="ps-input" type="search" autocomplete="off" spellcheck="false"/><button class="ps-search">搜索</button></div><div class="ps-status"></div><div class="ps-row"><button class="ps-nav ps-prev">上一个</button><button class="ps-nav ps-next">下一个</button><button class="ps-nav ps-clear">清除</button></div><details open><summary>结果</summary><div class="ps-result-list"></div></details><details><summary>历史</summary><div class="ps-history-list"></div></details><details><summary>配置</summary><label>位置<select class="ps-config-position"><option value="bottom">底部</option><option value="top">顶部</option><option value="topbar">顶栏</option></select></label><label><input class="ps-config-case" type="checkbox"/>区分大小写</label><label><input class="ps-config-regex" type="checkbox"/>正则</label><label><input class="ps-config-multi" type="checkbox" checked/>多关键字</label><label><input class="ps-config-iframes" type="checkbox" checked/>iframe</label><label><input class="ps-config-results" type="checkbox" checked/>显示结果</label><label><input class="ps-config-shortcut-enabled" type="checkbox" checked/>快捷键</label><input class="ps-config-shortcut" type="text" maxlength="1" value="k"/></details></div>`; document.documentElement.appendChild(el); applyAppearance(); renderHistory(); el.querySelector(".ps-toggle")?.addEventListener("click", () => el.classList.add("ps-open")); el.querySelector(".ps-search")?.addEventListener("click", search); el.querySelector(".ps-prev")?.addEventListener("click", () => go(-1)); el.querySelector(".ps-next")?.addEventListener("click", () => go(1)); el.querySelector(".ps-clear")?.addEventListener("click", () => { clear(); if (input()) input().value = "" }); el.querySelector(".ps-input")?.addEventListener("keydown", (e: any) => { if (e.key === "Enter") search(); if (e.key === "Escape") el.classList.remove("ps-open") }); el.addEventListener("click", (e: any) => { const r = e.target.closest?.(".ps-result"); if (r) { activeIndex = Number(r.dataset.index); updateActive() } const h = e.target.closest?.(".ps-history-item"); if (h && input()) { input().value = history[Number(h.dataset.index)] || ""; search() } }); el.addEventListener("input", handleConfigChange); el.addEventListener("change", handleConfigChange) }
  document.addEventListener("keydown", (event) => { if (config.shortcutEnabled && event.altKey && !event.metaKey && !event.ctrlKey && !event.shiftKey && event.key.toLowerCase() === String(config.shortcutKey || "k").toLowerCase()) { event.preventDefault(); root()?.classList.add("ps-open"); input()?.focus() } })
  ;(async () => { config = normalizeConfig(await loadStored(STORAGE_KEY, {})); history = normalizeHistory(await loadStored(HISTORY_KEY, [])); createPanel(); GM.registerMenuCommand?.("打开页面关键字搜索", () => root()?.classList.add("ps-open")) })()
})()
